version: "3"

services:
  geth:
    image: ethereum/client-go:v1.10.5
    container_name: geth
    ports:
      - "30303:30303"
      - "8546:8546"
      - "8545:8545"
      - "6060:6060"
    volumes:
      - ./data/geth:/root/.ethereum
    command: --metrics --metrics.addr 0.0.0.0  
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    volumes:
      - ./conf/prometheus/:/etc/prometheus/
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    # depends_on:
    #   - cadvisor
    restart: unless-stopped

  # cadvisor:  
  #   image: google/cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:rw
  #   ports: 
  #     - 8080:8080
  #   restart: always

  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./conf/grafana/custom.ini:/etc/grafana/custom.ini
      - ./conf/grafana/provisioning:/etc/grafana/provisioning
      - ./conf/grafana/dashboards:/var/lib/grafana
    restart: unless-stopped
    ports:
      - "3000:3000" 