{
 "title": "Geth statistics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Peers number",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2p_peers" }
   ]
  },
  {
   "title": "last synced",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_head_header", "legendFormat": "last header" },
    { "expr": "chain_head_block", "legendFormat": "last block" },
    { "expr": "chain_head_receipt", "legendFormat": "last receipt" }
   ]
  },
  {
   "title": "Disk ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_disk_readcount", "legendFormat": "{{ instance }} - read" },
    { "expr": "system_disk_writecount", "legendFormat": "{{ instance }} - write" }
   ]
  }
 ]
}